# Generated by Django 3.0.7 on 2021-06-02 13:06

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201015_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=post.models.user_directory_path),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
