# Generated by Django 3.1.5 on 2021-06-15 18:27

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20210602_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.ImageField(upload_to=post.models.user_directory_path),
        ),
    ]
