# Generated by Django 3.1.5 on 2021-06-15 18:38

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20210615_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.user_directory_path),
        ),
    ]
