# Generated by Django 3.0.7 on 2021-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storystream',
            name='story',
            field=models.ManyToManyField(related_name='stories', to='stories.Story'),
        ),
    ]
