# Generated by Django 3.1.5 on 2021-06-15 18:53

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210602_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.ImageField(upload_to=stories.models.user_directory_path),
        ),
    ]
